Milestone2
kelibst/react_calc pull request #2
Opened 2020-09-14 23:33 UTC by kelibst

- Implemented the App component 
- Implemented the Display component 
- Implemented the Button component 
- Implemented the ButtonPanel component

2020-09-15 13:30 UTC, Torres-ssf requested changes
### Changes required :muscle: 
Hi @kelibst :hand: 
Great job on this milestone so far :clap: 
We only need to make some small changes before moving on.

- [ ] We need to work on your README file. Right now it has only a few information about the Calculator app. We need to update the README file from the bootstrap text generated by `react-create-app` and add one with information about your project. You can use this nice template [here](https://github.com/microverseinc/readme-template), it will give a lot of value to your repository making it look more professional.
![Screenshot from 2020-09-09 09-17-52](https://user-images.githubusercontent.com/30977845/92597419-bdf4eb00-f27d-11ea-8964-a3a8dfdfdca0.png)

- [ ] I noticed that the linter is not set up on your repository. We need to check the [instructions here](https://github.com/microverseinc/linters-config/tree/master/react-redux) and set up the linter.yml file through Github actions.

Please kindly submit to code review again after making implementing these changes.
Feel free to message me on slack if you have any questions :smile: 
Happy Coding :computer: 
**Sergio Torres**

2020-09-15 23:57 UTC, uryelah requested changes
Hi **Keli Dogbevi**, I'm Sarah your reviewer for this PR 👩‍🚀 

Good job with this milestone! The way you setup the Button loop was very clever!

There's just a minor issue with the linter configuration, fixed by literally just copying and pasting the Microverse reccomended config, and with the name of the components, but as soon as you fix those details you are ready to go and rock your next milestones!

-------

# Required Changes 🏗️ 🐛 💡

(Check the comments below for the fixes)

-----

 **Kindly fix the pointed out issues and comments below before requesting the next code review**

------------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-09-15 23:57 UTC, uryelah commented on .eslintrc.json
> +{
- [ ] Good jobs setting the linter up! Just make sure the contents of the eslintrc are the same as the one in the [Microverse linters repo](https://github.com/microverseinc/linters-config/blob/master/javascript/.eslintrc.json).

2020-09-15 23:57 UTC, uryelah commented on src/components/ButtonCov.js
> +import SetButton from './setButton';
- [ ] Let's stick to the names in the Odin project instructions. It will make reading the code easier.
Change
SetButton -> Button
ButtonCov -> ButtonPanel
DisplayPanel -> Display

2020-09-15 23:57 UTC, uryelah commented on src/components/DisplayPanel.js
> +function DisplayPanel(props) {
- [ ] [OPTIONAL] You can do the object destructuring in the same line you have the props parameter:
` function DisplayPanel({ res }) { `

- [ ] [OPTIONAL] Use Arraw functions for a more ES6 flavor:
` const DisplayPane = ({ res }) => { `

2020-09-16 09:44 UTC, kelibst commented on .eslintrc.json
> +{
The linters repo link you provided was for JavaScript. This is a React Project. Find the linters [here](https://github.com/microverseinc/linters-config/blob/master/react-redux/.eslintrc.json)

2020-09-16 12:34 UTC, mosaaleb approved these changes
#### Well done @kelibst :clap:

I see that you have already handled all requirements from the previous reviews.

You can merge :+1:.
Good luck with the next milestones.

Just a minor tip on commit messages style guidelines. It's preferred to start your commit message with `change` instead of `changed`. Check this [out](https://commit.style/) for more.

##### Muhammad Ebeid

2020-09-16 13:20 UTC, merged